#!/usr/bin/with-contenv bash

echo "Installing Swift dependencies"
apt update && apt install binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata uuid-dev zlib1g-dev libpython3.10-dev -y

echo "Installing Swift binaries"
curl https://download.swift.org/swift-5.8-release/ubuntu2204/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04.tar.gz --output swift.tar.gz 
tar --strip-components=1 -zxf swift.tar.gz --directory /
rm swift.tar.gz

echo "Checking Swift version"
/usr/bin/swift -version

echo "Adding Swift to PATH for VSCode"
echo 'export PATH=/usr/bin:"${PATH}"' >> /config/.bashrc && source /config/.bashrc

echo "Swift binaries installed for VSCode. Trying to install the sswg.swift-lang extension"

install-extension sswg.swift-lang

echo "Please manually download and install 'sswg.swift-lang' from 'https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang' if you see errors above"
